Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false